export const testIds = {
  landing: {
    title: 'landing-title',
    signIn: 'landing-sign-in',
    accessNote: 'landing-access-note',
    privacy: 'landing-privacy',
  },
  auth: {
    email: 'auth-email',
    password: 'auth-password',
    displayName: 'auth-display-name',
    signInButton: 'auth-sign-in-button',
    signUpRestricted: 'auth-sign-up-restricted',
  },
  tabs: {
    home: 'tab-home',
    members: 'tab-members',
    tasks: 'tab-tasks',
    reports: 'tab-reports',
    more: 'tab-more',
  },
  home: {
    screen: 'home-screen',
    attentionList: 'home-attention-list',
  },
  members: {
    screen: 'members-screen',
    search: 'members-search',
    add: 'members-add',
    addForm: 'members-add-form',
    addSave: 'members-add-save',
    filter: (value: string) => `members-filter-${value}`,
    member: (id: string) => `member-item-${id}`,
  },
  memberProfile: {
    screen: 'member-profile-screen',
    logVisit: 'member-log-visit',
    careProgress: 'member-care-progress',
    assignmentRequest: 'member-assignment-request',
  },
  careProgress: {
    screen: 'care-progress-screen',
    notes: 'care-progress-notes',
    save: 'care-progress-save',
  },
  assignmentRequest: {
    screen: 'assignment-request-screen',
    reason: 'assignment-request-reason',
    submit: 'assignment-request-submit',
  },
  logVisit: {
    screen: 'log-visit-screen',
    save: 'log-visit-save',
    notes: 'log-visit-notes',
    type: (value: string) => `log-visit-type-${value}`,
  },
  tasks: {
    screen: 'tasks-screen',
    toggle: (id: string) => `task-toggle-${id}`,
  },
  reports: {
    screen: 'reports-screen',
    summary: 'reports-summary',
  },
  more: {
    screen: 'more-screen',
    signOut: 'more-sign-out',
    privacy: 'more-privacy',
  },
  admin: {
    entry: 'admin-entry',
    center: 'admin-center',
    unauthorized: 'admin-unauthorized',
    menu: (id: string) => `admin-menu-${id}`,
    users: { screen: 'admin-users-screen' },
    congregations: { screen: 'admin-congregations-screen' },
    members: {
      screen: 'admin-members-screen',
      add: 'admin-members-add',
      form: 'admin-member-form',
      save: 'admin-member-save',
      assignShepherd: (id: string) => `admin-member-assign-${id}`,
      item: (id: string) => `admin-member-${id}`,
    },
    tasks: {
      screen: 'admin-tasks-screen',
      add: 'admin-tasks-add',
      form: 'admin-task-form',
      save: 'admin-task-save',
      assignShepherd: (id: string) => `admin-task-assign-${id}`,
      item: (id: string) => `admin-task-${id}`,
    },
    reports: { screen: 'admin-reports-screen' },
    controls: { screen: 'admin-controls-screen' },
    assignmentRequests: {
      screen: 'admin-assignment-requests-screen',
      approve: (id: string) => `admin-assignment-approve-${id}`,
      reject: (id: string) => `admin-assignment-reject-${id}`,
    },
  },
  notifications: {
    status: 'notifications-status',
    enable: 'notifications-enable',
  },
  toast: 'app-toast',
} as const;
