import type { Member, Task } from '@/types/database';

const now = new Date().toISOString();

export const demoMembers: Member[] = [
  {
    id: '1',
    full_name: 'Sarah Mkhize',
    phone: '+27 82 123 4567',
    email: 'sarah.mkhize@example.com',
    address: 'Durban North',
    risk_level: 'high',
    status: 'inactive',
    last_contact_at: '2026-04-10T10:00:00.000Z',
    notes: 'Missed last two meetings.',
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '2',
    full_name: 'Daniel Khumalo',
    phone: '+27 83 234 5678',
    email: null,
    address: 'Pinetown',
    risk_level: 'high',
    status: 'active',
    last_contact_at: '2026-04-15T10:00:00.000Z',
    notes: null,
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '3',
    full_name: 'Sipho Dlamini',
    phone: '+27 84 345 6789',
    email: null,
    address: 'Westville',
    risk_level: 'medium',
    status: 'new',
    last_contact_at: '2026-05-01T10:00:00.000Z',
    notes: 'Recently baptized.',
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '4',
    full_name: 'Thandiwe Nkosi',
    phone: '+27 85 456 7890',
    email: null,
    address: 'Chatsworth',
    risk_level: 'high',
    status: 'active',
    last_contact_at: '2026-03-20T10:00:00.000Z',
    notes: null,
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '5',
    full_name: 'Nomsa Zulu',
    phone: '+27 86 567 8901',
    email: null,
    address: 'Umhlanga',
    risk_level: 'low',
    status: 'active',
    last_contact_at: '2026-05-20T10:00:00.000Z',
    notes: null,
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '6',
    full_name: 'Sibusiso Buthelezi',
    phone: '+27 87 678 9012',
    email: null,
    address: 'Ballito',
    risk_level: 'low',
    status: 'active',
    last_contact_at: '2026-05-18T10:00:00.000Z',
    notes: null,
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: '7',
    full_name: 'Lindiwe Cele',
    phone: '+27 88 789 0123',
    email: null,
    address: 'Phoenix',
    risk_level: 'medium',
    status: 'new',
    last_contact_at: '2026-05-10T10:00:00.000Z',
    notes: null,
    assigned_to: null,
    created_at: now,
    updated_at: now,
  },
];

export const demoTasks: Task[] = [
  {
    id: 't1',
    title: '5 Calls',
    description: 'Follow up with assigned members',
    assignee_id: null,
    member_id: null,
    due_date: '2026-05-26',
    status: 'open',
    priority: 'high',
    task_type: 'call',
    created_at: now,
    updated_at: now,
  },
  {
    id: 't2',
    title: '2 Hospital Visits',
    description: 'Visit members in hospital',
    assignee_id: null,
    member_id: null,
    due_date: '2026-05-27',
    status: 'open',
    priority: 'high',
    task_type: 'visit',
    created_at: now,
    updated_at: now,
  },
  {
    id: 't3',
    title: '1 Bible Study',
    description: 'Weekly study session',
    assignee_id: null,
    member_id: '3',
    due_date: '2026-05-28',
    status: 'open',
    priority: 'medium',
    task_type: 'bible_study',
    created_at: now,
    updated_at: now,
  },
  {
    id: 't4',
    title: 'Visit 3 Families',
    description: 'Monthly family visits',
    assignee_id: null,
    member_id: null,
    due_date: '2026-05-30',
    status: 'open',
    priority: 'medium',
    task_type: 'visit',
    created_at: now,
    updated_at: now,
  },
  {
    id: 't5',
    title: 'Follow up with New Converts',
    description: 'Check in with recent baptisms',
    assignee_id: null,
    member_id: null,
    due_date: '2026-06-01',
    status: 'open',
    priority: 'high',
    task_type: 'other',
    created_at: now,
    updated_at: now,
  },
  {
    id: 't6',
    title: 'Elder Meeting',
    description: 'Monthly coordination meeting',
    assignee_id: null,
    member_id: null,
    due_date: '2026-06-05',
    status: 'open',
    priority: 'low',
    task_type: 'meeting',
    created_at: now,
    updated_at: now,
  },
];
